server:
  port: 8787
  servlet:
    encoding:
      force-response: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinepeople
    username: root
    password: 1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database : mysql
    hibernate.ddl-auto : create
    default_batch_fetch_size: 1000
    hibernate.naming.strategy : org.hibernate.cfg.SpringPhysicalNamingStrategy
    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl : false

jwt:
  token:
    secret: hello